# Generated by Django 2.1.2 on 2018-11-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20181104_1255'),
        ('usuarios', '0002_auto_20181104_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='favsuser',
            name='receta_fav',
            field=models.ManyToManyField(related_name='favoritas', to='apis.Receta'),
        ),
    ]
