# Generated by Django 2.1.2 on 2018-10-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Receta')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('passw', models.CharField(blank=True, max_length=50)),
                ('recetas', models.ManyToManyField(through='apis.Favorito', to='apis.Receta')),
            ],
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User'),
        ),
    ]
