# Generated by Django 2.1.2 on 2018-10-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0002_auto_20181017_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecetasCreadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Receta')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.CustomUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='recetas',
        ),
        migrations.AlterField(
            model_name='favorito',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.CustomUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='recetas_creadas',
            field=models.ManyToManyField(related_name='creadas', through='apis.RecetasCreadas', to='apis.Receta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recetas_fav',
            field=models.ManyToManyField(related_name='favoritas', through='apis.Favorito', to='apis.Receta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
